config/applications.json, controller/application.go
- add save apps function to save application
- create unzip file function from colony manager to colony app
=> add saveapps function and unzip

assets/core/page-application.js, views/page-application.html
Update file budianto 15:47 5-2-2016
=> Budianto incolony3 Update file budianto 15:47 5-2-2016

controller/datagrabber.go
=> remove cron

controller/datagrabber.go
pass pointer of datagrabber instance instead
=> fix bug on datagrabber `starttransformation`

assets/core/page-server.js, controller/application.go, controller/server.go
=> multi delete apps & server

controller/application.go, views/page-application.html
=> update view 16-2-2016 5:18pm

assets/core/page-datagrabber.js, views/page-datagrabber.html
=> Data to treeview and test treeview hierarchy

controller/application.go
Update Create, Remove, Edit/Save Files
=> Update Create, Remove, Edit/Save Files

assets/core/page-application.js, views/page-application.html
Menambahkan popup ketika delete / update file
=> Mengganti css button "refresh" dan "save" di editor

assets/core/page-application.js, controller/application.go
Fix bug application editor when the file has no extension and folder has dot (.) on the name, blank text editor when click the folder, bug when create new file being the folder
=> Fix bug check the file/folder based on its original type not the name

assets/core/style.sass, views/page-application.html, views/page-datasource.html
- mengganti warna button (Save dan Test Connection) di halaman detail datasource 
- mengganti warna border pada editor halaman aplication.
=> change colors button and border

assets/core/page-datagrabber.js
- show data when click edit data grabber
=> - show data when click edit

assets/core/page-datagrabber.js
fix bug show data when click edit
=> fix bug show data when click edit

assets/core/page-datagrabber.js
check data type source and destination
=> check data type source and destination

assets/core/page-webgrabber.js, views/page-webgrabber.html
i'm sorry for so many additions and deletions cause i use netbeans as editor and make the code auto format. Actually i just change some codes. :3
=> implements new config on the UI - webgrabber

controller/datasource.go, helper/query.go
=> hive connection

colony.go, controller/databrowser.go
add controller databrowser with one filter contains
=> add controller databrowser with one filter contains

controller/application.go
=> modif for ubuntu

assets/core/page-databrowserdesign.js, views/page-databrowserdesign.html
- table editable
- use combobox on connection list and table list
=> update data browser dsign

views/page-databrowserdesign.html
i mark some div please ask me if there something wrong
=> update data-browserdesign 26-2-2016 9:19am

assets/core/page-application.js, assets/core/page-datasource.js, assets/core/page-server.js, views/page-application.html, views/page-datasource.html
menu delete when click edit data connection list & data source
=> menu delete when click edit data connection list & data source

assets/core/page-application.js
=> - fix delete page application

assets/core/page-application.js
- fix bug delete page-aplication
=> - fix bug delete page-aplication

assets/core/page-datagrabber.js, views/layout.html, views/page-datagrabber.html
=> - add new page data wizard

controller/webgrabber.go
func view history
func view log
func stopped and running
=> func stopped and running

assets/core/page-datagrabber.js, views/page-datagrabber.html
=> - fix page data wizard

controller/databrowser.go, controller/datasource.go
Pull Request in data browser add paging and filter
=> Data browser add filter and paging

assets/core/page-databrowser.js, views/page-databrowser.html
=> update budi ui databrowser 1-3-2016 7:57pm

assets/core/page-datagrabber.js
- fix drop downlist connection source & data source
=> - fix drop downlist connection source & data source

assets/core/page-datagrabber.js, views/page-datagrabber.html
=> - function save data wizard

views/page-datagrabber.html
=> - update prefix

assets/core/page-datagrabber.js, views/page-datagrabber.html
- add alert when input user empty page wizard
=> - add alert when input user empty page wizard

assets/core/page-webgrabber.js, controller/webgrabber.go
Can’t automatically merge. Don’t worry, you can still create the pull request
=> Commit Add Note Config webgrabber

assets/core/page-databrowser-query.js, assets/core/page-databrowser.js, assets/core/page-databrowserdesign.js, controller/databrowser.go, views/page-databrowserdesign.html
query builder dbox on databrowser
=> query builder dbox on databrowser

assets/core/page-application.js, controller/application.go, views/page-application.html
=> command & variable

assets/databrowser/ecdatabrowser.js, controller/databrowser.go
- fix bug cannot get type of nil value
- make the grid columns scrollable if it has many columns
=> changes Data Browser

assets/core/page-databrowser-query.js, assets/core/page-databrowserdesign.js, controller/databrowser.go, views/page-databrowserdesign.html
bug fix for databrowser freequery
=> bug fix for databrowser freequery

assets/core/page-application.js, controller/application.go, controller/server.go, views/page-application.html
ramake unzip & remove command,variable
=> ramake unzip

views/page-datagrabber.html
=> - prefix can be empty

assets/core/page-webgrabber.js, assets/filebrowser/ecfilebrowser.js, controller/filebrowser.go, controller/webgrabber.go, views/page-application.html, views/page-webgrabber.html
- allow all kind of driver
- filter only sourcetype_html type data shown on the grid
- fix some layouts
- fix bug on edit, connection id is empty
- fix bug on edit, condition list list invalid
- fix bug on edit, filter condition is empty
- add delete button on column selector
- resize the filter
- fix download file from node server
=> changes on Web Grabb, File Browser, Application

assets/core/page-server.js, assets/filebrowser/ecfilebrowser.js
- fix bug cannot show data from hdfs
- add error handler for all ajaxes
=> # File Browser

assets/core/page-datagrabber.js, controller/databrowser.go, controller/datasource.go
- fix bug cannot save data serializer (reason the function was overrided by save wizard)
- fix bug cannot fetch data source origin values
- fix bug meta data always not success
=> changes on Data Serializer

assets/databrowser/ecdatabrowser.js, controller/server.go
- fix bug cannot add hadoop server
=> changes on Server

controller/datasource.go
- fix bug try to get metadata from empty results
=> changes on Data Source

assets/core/page-databrowserdesign.js, controller/databrowser.go, controller/datasource.go, views/page-databrowserdesign.html
bug fix UI & query pattern for range filter on databrowser
=> bug fix UI & query pattern

controller/application.go, views/page-application.html, views/page-servers.html
- fix bug deleting variable/function make the page reloaded
- empty destination path first before extract uploaded application
- fix bug deleting references make the page reloaded
=> changes on Server & Application

assets/core/page-databrowserdesign.js, controller/databrowser.go, controller/datasource.go
=> filter with lookup UI

assets/core/page-application.js, assets/core/page-server.js, controller/application.go, views/page-servers.html
- change the structure of saved host aliases
- hide error from removing destination path before deploying app
- fix bug tree view loaded when the first time
=> changes on App & Server

helper/helper.go
- move permission check to helper
=> changes on Other

assets/core/page-datagrabber.js, views/page-datagrabber.html
change dg.config to dg.configWizard
=> change dg.config to dg.configWizard

controller/databrowser.go
- fixed aggregate for sql free text query
=> databrowser aggregate

assets/core/page-datagrabber.js, views/page-datagrabber.html
- fix save data table source & destination
=> - fix save data table source & destination

controller/datasource.go
distinct value on lookup databrowser for mongo & rdbms
=> distinct value on lookup databrowser

controller/datasource.go
=> parse filter datatype

assets/core/page-administration.js, assets/core/page-group.js, assets/core/page-user.js, controller/administration.go, controller/app.go, controller/application.go, controller/datasource.go, controller/group.go, controller/user.go, views/page-administration.html, views/page-group.html, views/page-user.html
implement acl into colonymanager
=> implement acl into colonymanager

assets/core/page-databrowser.js, assets/databrowser/ecdatabrowser.js, controller/datasource.go
databrowser bug fix & distinct value on flat file
=> databrowser bug fix & distinct value

assets/core/page-datagrabber.js
- Fix bug hidden button Sync
- Remove table header when user klick empty connection source
- user must chose connection source first
=> Form add wizard data serializer:

assets/core/page-databrowserdesign.js, views/page-databrowserdesign.html
- hide aggregate column for flat files (json, jsons, csv, csvs)
- clear metadata on populate table
=> hide aggregate

assets/core/page-administration.js, assets/core/page-group.js, assets/core/page-user.js, colony.go, controller/administration.go, controller/group.go, controller/user.go, views/page-administration.html, views/page-group.html, views/page-user.html
create grid user,group, access for acl
=> create grid user,group, access for acl 

assets/core/page-administration.js, assets/core/page-group.js, assets/core/page-user.js, colony.go, controller/administration.go, controller/application.go, controller/group.go, controller/server.go, controller/user.go, controller/webgrabber.go, controller/webgrabberapi.go, views/page-administration.html, views/page-group.html, views/page-user.html
- on creation deploy sedotan on server
- start/stop sedotan on server
=> changes on Server & Web Grabber

colony.go, controller/acl.go
=> add acl rest

controller/datasource.go
- convert setting value to better data type
=> changes Connection

controller/webgrabber.go
=> format expired time and start time

controller/server.go
=> no message

controller/datasource.go, helper/query.go
=> # Connection

assets/core/page-group.js, assets/core/page-user.js, controller/filebrowser.go, controller/group.go, views/page-group.html, views/page-user.html
=> fix accessgrant group

assets/core/page-webgrabber.js, controller/webgrabber.go
- fix bug blink appear when get snapshot
- fix bug status always changed to "stopped" after get snapshot
- need to replace "localhost" to current IP address, when the config file is deployed onto server
=> changes on Web Grabber

assets/core/page-administration.js, assets/core/page-group.js, assets/core/page-user.js, controller/administration.go, controller/group.go, controller/user.go, views/page-administration.html, views/page-group.html, views/page-user.html
add filter, modify multi select group , add knockoutooltip
=> add filter, modify multi select group , add knockoutooltip

assets/core/page-session.js, controller/session.go, views/page-session.html
Page session and filter #example
=> Page session and filter

assets/core/page-administration.js, controller/administration.go, controller/session.go, views/page-administration.html
=> Server paging and bug fix

assets/core/page-group.js, assets/core/page-user.js, views/page-administration.html, views/page-group.html, views/page-user.html
=> modify ui user

assets/core/page-application.js, views/page-application.html
page application :
- create menu language enviroment
- create table language enviroment (data : server with type node)
=> page application :

colony.go, controller/app.go, controller/web.go, controller/widgetgrid.go
save & get data for grid widget
=> save & get data for grid widget

assets/core/page-administration.js, controller/web.go, views/page-administration.html, views/page-user.html
Some bug fix in user and group
=> Some bug fix in user and group

controller/widgetgrid.go, controller/widgetselector.go, helper/helper.go
- add controller function for getting data, saving & removing widget
selector
- add controller function for getting data & saving widget grid
- add get datasource for query only on helper
=> widget select & grid

assets/core/page-application.js, views/page-application.html
- Create function setup to setting language
=> - Create function setup to setting language

assets/core/page-widgetgrid.js, controller/widgetgrid.go
create new getting & saving method on widget grid
=> new getting & saving method on widget grid

assets/core/page-widgetgrid.js, controller/widgetgrid.go, views/page-widgetgrid.html
create function save, delete, get data and edit data for widget grid
=> widget grid controller

assets/core/page-application.js
- fix the data to send when click setup
- add alert user error
=> - fix the data to send when click setup & add alert user error

assets/core/page-user.js, controller/user.go, views/page-user.html
fix bug user and modify search
=> fix bug user and modify search

controller/widgetchart.go
=> controller for widget chart

assets/core/page-application.js
- fix alert message when user forget to select language
- add check all language
=> language Enviroment :

controller/widgetchart.go, controller/widgetgrid.go
update widget chart & grid controller
=> update widget chart & grid controller

assets/core/page-application.js, views/page-application.html
Language Enviroment : 
- remove button setup
- change checkbox langgue to button
- server type = node
=> Language Enviroment : 

colony.go, controller/app.go, controller/web.go, controller/widget.go, controller/widgetselector.go
widget controller to handle insert, update, delete, upload & extract file
=> widget controller

controller/widget.go
=> fetch data source

controller/page.go, controller/widget.go
add func walk & page controller
=> add func walk & page controller

assets/core/page-application.js, controller/langenvironment.go, views/page-application.html
create function in controller to get data language
=> create controller to get data language

assets/core/page-user.js, controller/user.go, views/page-user.html
fix bug ldap user & add search
=> fix bug add ldap user & add search

assets/core/page-application.js
delete function apl.getLangEnv & apl.getLanguage
=> delete function apl.getLangEnv & apl.getLanguage

assets/core/page-languageenvironment.js, controller/app.go, views/page-application.html, views/page-langenvi.html
language environment :
- create grid dynamic column by data language
- create new file html page-langenvi.html, move script language environemt to page-langenvi from page-application.hmtl
=> language environment : create grid dynamic column by data language, move script language environemt to page-langenvi from page-application.hmtl

controller/page.go
=> upload file to server

controller/page.go
=> update page controller

controller/page.go, controller/widget.go
- add function to fetch data from datasource
- add function get field name from datasource
=> get data from datasource

assets/core/page-languageenvironment.js, controller/langenvironment.go, views/page-langenvi.html
Language Environment :
- create grid dynamic column
- create function search
=> Language Environment : create grid dynamic column & function search

colony.go, controller/acl.go, controller/login.go, controller/user.go
bug fix and add some feature to implement acl in colony
=> bug fix and add some feature to implement acl in colony

assets/core/page-languageenvironment.js
- create function to send data to controller
- make button setup language disable when status isinstaled = true
=> Language environment : 

controller/page.go
add save page and save designer
=> update page widget controller

assets/core/page-languageenvironment.js
make button setup disable when status IsInstalled = true
=> make button setup disable when status IsInstalled = true

assets/core/page-languageenvironment.js, views/page-langenvi.html
create alert & add miniloader in language environmnt
=> - create alert & add miniloader in language environmnt

controller/page.go, controller/widget.go, helper/helper.go, helper/query.go
Widget.go
- move FetchDataFromDS function from widget to helper
Page.go
- move GetFieldsFromDS funcction from page widget to helper
- update GetAllFields function so it can return all field each
datasource and content string from html
- add EditPageDesigner function to send page data by id to the UI
- PreviewExample function (on progress)
Helper.go
- move  GetDataSourceQuery function from helper.go to query.go
Query.go
- add several function to query data from datasource, such as :
- ConnectToDataSource
- GetDataSourceQuery
- checkIfDriverIsSupported
- FetchDataFromDS
- GetFieldsFromDS
- ParseQuery
- FilterParse
=> update widget, page and helper

assets/core/page-languageenvironment.js, views/page-langenvi.html
create filter language environment
=> create filter language environment

assets/core/page-languageenvironment.js, views/page-langenvi.html
- create text please wait when loading
=> - create text please wait when loading

controller/page.go, controller/widget.go
save new widget & bug fix URL on widget
=> update widget & page controller

assets/core/page-group.js, assets/core/page-user.js, views/page-group.html
=> update ui  11-4-2016 9:26am

controller/page.go, controller/widget.go
=> update widget page controller

assets/core/page-languageenvironment.js
- create function & add icon to remove language
=> - create function & add icon to remove language

assets/core/page-languageenvironment.js
- change tittle setup & remove to install & uninstall
=> - change tittle setup & remove to install & uninstall

assets/core/page-application.js
- fix bug filter when click create new application or select data grid
=> - fix bug filter when click create new application or select data grid

assets/core/page-widget.js, views/page-widget.html
- create new grid style in widget list
- add function for button priview, edit
=> create new grid style in widget list & add function for button priview, edit

assets/core/page-widget.js, views/page-widget.html
- change function button preview, setting
- delete widget
=> - change function button preview, setting

assets/core/page-widget.js, views/page-widget.html
- fix bug colum search
- delete widget
=> - fix bug colum search - delete widget

assets/core/page-designer-editor.js, assets/gridstack/gridstack.js
- Fix bug drag n drop windget
- Delete widget
=> - Fix bug drag n drop windget & delete widget

assets/core/page-designer.js
- insert data ko.mapping config page
=> - insert data ko.mapping config page

assets/core/museum/page-designer.js, assets/core/page-view.js, controller/pagedesigner.go, views/page-view.html
mas please ignore page-designer.js i had wrong file to attach,  it's must be page-view.js please forgive me it's make conflict
=> update page preview

assets/core/layout.js, assets/core/page-session.js, views/layout.html
=> update comit login fix bug

assets/core/layout.js, controller/login.go
=> comit login

assets/core/page-view.js, views/page-view.html
=> update page view

assets/core/page-view.js, colony.go, controller/page.go
=> update golang page view

assets/core/page-pages.js
- create function delete page
- fix bug checkbox all when click edit and back to front page
=> create function delete page

assets/core/page-pages.js, views/page-pages.html
- fix search menu page
- add miniloader in menu page
=> - fix heading tittle create new & edit page

assets/core/page-pages.js, assets/core/page-view.js
=> - create button preview

assets/core/page-pages.js, assets/core/page-view.js, views/page-view.html
- create width & height widgate
=> - create width & height widgate

assets/core/page-view.js, views/page-view.html
=> create tittle widget

views/page-servers.html
- Make Other Services tab hide when create new server
- create error message cannot be empty in SSH host, user & password when click save
=> Page-severs

assets/core/page-application.js, views/page-application.html
Application :
- create field Language
- create function to get data language
=> Application :

assets/core/page-application.js, views/page-application.html
- create field langue hide when value != web
=> - create field langue hide when value != web

controller/application.go, helper/helper.go
=> update colony manager 

assets/core/page-designer.js, views/page-designer.html
- create stylesheet using codemirror
=> - create stylesheet using codemirror

assets/core/page-datagrabber.js, assets/core/page-datasource.js, assets/core/page-designer.js, assets/core/page-server.js
fix bug load data in stylesheet
=> - fix bug load data in stylesheet

views/page-application.html
=> commit update aplication

assets/core/layout.js, assets/core/page-datagrabber.js, views/layout.html
=> update datagrabber save mode

assets/core/page-application.js, assets/core/page-designer.js, assets/core/page-server.js, views/page-designer.html, views/page-servers.html
fix bug getdatalanguage in appliction
=> - fix bug getdatalanguage in appliction

assets/core/page-application.js
- fix bug start-stop button not working
=> # Application
